Building DAG of jobs...
shared_storage_local_copies: True
remote_exec: False
Using shell: /usr/bin/bash
Provided cores: 24
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job stats:
job         count
--------  -------
all             1
dupradar        6
total           7

Resources before job selection: {'_cores': 24, '_nodes': 9223372036854775807}
Ready jobs (6)
Select jobs to execute...
Selected jobs (4)
Resources after job selection: {'_cores': 0, '_nodes': 9223372036854775803}
Execute 4 jobs...

[Sun Aug 18 23:49:00 2024]
Job 62: RAP1_REP1_treatment: Running dupRadar to evaluate technical and biological read duplication
Reason: Missing output files: results/dupradar/RAP1_REP1_treatment/RAP1_REP1_treatment_mqc.txt, results/dupradar/RAP1_REP1_treatment/RAP1_REP1_treatment.dupradar.pdf, results/dupradar/RAP1_REP1_treatment/RAP1_REP1_treatment.dupradar.txt


[Sun Aug 18 23:49:00 2024]
Job 60: WT_REP2_control: Running dupRadar to evaluate technical and biological read duplication
Reason: Missing output files: results/dupradar/WT_REP2_control/WT_REP2_control.dupradar.txt, results/dupradar/WT_REP2_control/WT_REP2_control.dupradar.pdf, results/dupradar/WT_REP2_control/WT_REP2_control_mqc.txt


[Sun Aug 18 23:49:00 2024]
Job 63: RAP1_REP2_treatment: Running dupRadar to evaluate technical and biological read duplication
Reason: Missing output files: results/dupradar/RAP1_REP2_treatment/RAP1_REP2_treatment.dupradar.txt, results/dupradar/RAP1_REP2_treatment/RAP1_REP2_treatment.dupradar.pdf, results/dupradar/RAP1_REP2_treatment/RAP1_REP2_treatment_mqc.txt


[Sun Aug 18 23:49:00 2024]
Job 59: WT_REP1_control: Running dupRadar to evaluate technical and biological read duplication
Reason: Missing output files: results/dupradar/WT_REP1_control/WT_REP1_control.dupradar.pdf, results/dupradar/WT_REP1_control/WT_REP1_control.dupradar.txt, results/dupradar/WT_REP1_control/WT_REP1_control_mqc.txt

Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 1266, in __rule_dupradar
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        scripts/dupradar.r results/align/bam_markup/RAP1_REP1_treatment/RAP1_REP1_treatment.markdup.sorted.bam resources/annotation.filtered.gtf 2 paired' returned non-zero exit status 1.

Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 1266, in __rule_dupradar
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        scripts/dupradar.r results/align/bam_markup/RAP1_REP1_treatment/RAP1_REP1_treatment.markdup.sorted.bam resources/annotation.filtered.gtf 2 paired' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 261, in _callback
    raise ex
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 247, in cached_or_run
    run_func(*args)
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 459, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 623:
Command 'set -euo pipefail;  
        scripts/dupradar.r results/align/bam_markup/RAP1_REP1_treatment/RAP1_REP1_treatment.markdup.sorted.bam resources/annotation.filtered.gtf 2 paired' returned non-zero exit status 1.

RuleException:
CalledProcessError in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 623:
Command 'set -euo pipefail;  
        scripts/dupradar.r results/align/bam_markup/RAP1_REP1_treatment/RAP1_REP1_treatment.markdup.sorted.bam resources/annotation.filtered.gtf 2 paired' returned non-zero exit status 1.
[Sun Aug 18 23:49:00 2024]
Error in rule dupradar:
    jobid: 62
    input: results/align/bam_markup/RAP1_REP1_treatment/RAP1_REP1_treatment.markdup.sorted.bam, resources/annotation.filtered.gtf
    output: results/dupradar/RAP1_REP1_treatment/RAP1_REP1_treatment.dupradar.pdf, results/dupradar/RAP1_REP1_treatment/RAP1_REP1_treatment.dupradar.txt, results/dupradar/RAP1_REP1_treatment/RAP1_REP1_treatment_mqc.txt
    log: logs/dupradar/RAP1_REP1_treatment.log (check log file(s) for error details)
    conda-env: /home/lucianhu/rna_snakemake/test_ting/.snakemake/conda/f3a668c38aeba1e7912f94bfdde9873f_
    shell:
        
        scripts/dupradar.r results/align/bam_markup/RAP1_REP1_treatment/RAP1_REP1_treatment.markdup.sorted.bam resources/annotation.filtered.gtf 2 paired
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 1266, in __rule_dupradar
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        scripts/dupradar.r results/align/bam_markup/WT_REP1_control/WT_REP1_control.markdup.sorted.bam resources/annotation.filtered.gtf 2 paired' returned non-zero exit status 1.

Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 1266, in __rule_dupradar
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        scripts/dupradar.r results/align/bam_markup/RAP1_REP2_treatment/RAP1_REP2_treatment.markdup.sorted.bam resources/annotation.filtered.gtf 2 paired' returned non-zero exit status 1.

Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 1266, in __rule_dupradar
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        scripts/dupradar.r results/align/bam_markup/WT_REP1_control/WT_REP1_control.markdup.sorted.bam resources/annotation.filtered.gtf 2 paired' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 261, in _callback
    raise ex
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 247, in cached_or_run
    run_func(*args)
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 459, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 623:
Command 'set -euo pipefail;  
        scripts/dupradar.r results/align/bam_markup/WT_REP1_control/WT_REP1_control.markdup.sorted.bam resources/annotation.filtered.gtf 2 paired' returned non-zero exit status 1.

RuleException:
CalledProcessError in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 623:
Command 'set -euo pipefail;  
        scripts/dupradar.r results/align/bam_markup/WT_REP1_control/WT_REP1_control.markdup.sorted.bam resources/annotation.filtered.gtf 2 paired' returned non-zero exit status 1.
Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 1266, in __rule_dupradar
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        scripts/dupradar.r results/align/bam_markup/RAP1_REP2_treatment/RAP1_REP2_treatment.markdup.sorted.bam resources/annotation.filtered.gtf 2 paired' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 261, in _callback
    raise ex
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 247, in cached_or_run
    run_func(*args)
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 459, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 623:
Command 'set -euo pipefail;  
        scripts/dupradar.r results/align/bam_markup/RAP1_REP2_treatment/RAP1_REP2_treatment.markdup.sorted.bam resources/annotation.filtered.gtf 2 paired' returned non-zero exit status 1.

[Sun Aug 18 23:49:00 2024]
Error in rule dupradar:
    jobid: 59
    input: results/align/bam_markup/WT_REP1_control/WT_REP1_control.markdup.sorted.bam, resources/annotation.filtered.gtf
    output: results/dupradar/WT_REP1_control/WT_REP1_control.dupradar.pdf, results/dupradar/WT_REP1_control/WT_REP1_control.dupradar.txt, results/dupradar/WT_REP1_control/WT_REP1_control_mqc.txt
    log: logs/dupradar/WT_REP1_control.log (check log file(s) for error details)
    conda-env: /home/lucianhu/rna_snakemake/test_ting/.snakemake/conda/f3a668c38aeba1e7912f94bfdde9873f_
    shell:
        
        scripts/dupradar.r results/align/bam_markup/WT_REP1_control/WT_REP1_control.markdup.sorted.bam resources/annotation.filtered.gtf 2 paired
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

RuleException:
CalledProcessError in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 623:
Command 'set -euo pipefail;  
        scripts/dupradar.r results/align/bam_markup/RAP1_REP2_treatment/RAP1_REP2_treatment.markdup.sorted.bam resources/annotation.filtered.gtf 2 paired' returned non-zero exit status 1.
[Sun Aug 18 23:49:00 2024]
Error in rule dupradar:
    jobid: 63
    input: results/align/bam_markup/RAP1_REP2_treatment/RAP1_REP2_treatment.markdup.sorted.bam, resources/annotation.filtered.gtf
    output: results/dupradar/RAP1_REP2_treatment/RAP1_REP2_treatment.dupradar.pdf, results/dupradar/RAP1_REP2_treatment/RAP1_REP2_treatment.dupradar.txt, results/dupradar/RAP1_REP2_treatment/RAP1_REP2_treatment_mqc.txt
    log: logs/dupradar/RAP1_REP2_treatment.log (check log file(s) for error details)
    conda-env: /home/lucianhu/rna_snakemake/test_ting/.snakemake/conda/f3a668c38aeba1e7912f94bfdde9873f_
    shell:
        
        scripts/dupradar.r results/align/bam_markup/RAP1_REP2_treatment/RAP1_REP2_treatment.markdup.sorted.bam resources/annotation.filtered.gtf 2 paired
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 1266, in __rule_dupradar
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        scripts/dupradar.r results/align/bam_markup/WT_REP2_control/WT_REP2_control.markdup.sorted.bam resources/annotation.filtered.gtf 2 paired' returned non-zero exit status 1.

Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 1266, in __rule_dupradar
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        scripts/dupradar.r results/align/bam_markup/WT_REP2_control/WT_REP2_control.markdup.sorted.bam resources/annotation.filtered.gtf 2 paired' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 261, in _callback
    raise ex
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 247, in cached_or_run
    run_func(*args)
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 459, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 623:
Command 'set -euo pipefail;  
        scripts/dupradar.r results/align/bam_markup/WT_REP2_control/WT_REP2_control.markdup.sorted.bam resources/annotation.filtered.gtf 2 paired' returned non-zero exit status 1.

RuleException:
CalledProcessError in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 623:
Command 'set -euo pipefail;  
        scripts/dupradar.r results/align/bam_markup/WT_REP2_control/WT_REP2_control.markdup.sorted.bam resources/annotation.filtered.gtf 2 paired' returned non-zero exit status 1.
[Sun Aug 18 23:49:00 2024]
Error in rule dupradar:
    jobid: 60
    input: results/align/bam_markup/WT_REP2_control/WT_REP2_control.markdup.sorted.bam, resources/annotation.filtered.gtf
    output: results/dupradar/WT_REP2_control/WT_REP2_control.dupradar.pdf, results/dupradar/WT_REP2_control/WT_REP2_control.dupradar.txt, results/dupradar/WT_REP2_control/WT_REP2_control_mqc.txt
    log: logs/dupradar/WT_REP2_control.log (check log file(s) for error details)
    conda-env: /home/lucianhu/rna_snakemake/test_ting/.snakemake/conda/f3a668c38aeba1e7912f94bfdde9873f_
    shell:
        
        scripts/dupradar.r results/align/bam_markup/WT_REP2_control/WT_REP2_control.markdup.sorted.bam resources/annotation.filtered.gtf 2 paired
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-08-18T234900.389311.snakemake.log
unlocking
removing lock
removing lock
removed all locks
Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/cli.py", line 2103, in args_to_api
    dag_api.execute_workflow(
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/api.py", line 594, in execute_workflow
    workflow.execute(
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/workflow.py", line 1286, in execute
    raise WorkflowError("At least one job did not complete successfully.")
snakemake_interface_common.exceptions.WorkflowError: At least one job did not complete successfully.

WorkflowError:
At least one job did not complete successfully.
