Building DAG of jobs...
Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/dag.py", line 2070, in collect_potential_dependencies
    yield PotentialDependency(file, known_producers[file], True)
                                    ~~~~~~~~~~~~~~~^^^^^^
KeyError: 'results/align/bam_original/WT_REP1_control/WT_REP1_control.Aligned.out.bam'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/cli.py", line 2103, in args_to_api
    dag_api.execute_workflow(
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/api.py", line 594, in execute_workflow
    workflow.execute(
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/workflow.py", line 1081, in execute
    self._build_dag()
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/workflow.py", line 1037, in _build_dag
    async_run(self.dag.init())
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/common/__init__.py", line 94, in async_run
    return asyncio.run(coroutine)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/dag.py", line 179, in init
    job = await self.update([job], progress=progress, create_inventory=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/dag.py", line 1013, in update
    raise exceptions[0]
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/dag.py", line 970, in update
    await self.update_(
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/dag.py", line 1055, in update_
    potential_dependencies = [
                             ^
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/dag.py", line 2088, in collect_potential_dependencies
    await file2jobs(
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/dag.py", line 2189, in file2jobs
    raise exceptions[0]
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/dag.py", line 2181, in file2jobs
    await self.new_job(
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/dag.py", line 1927, in new_job
    job = await self.job_factory.new(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/jobs.py", line 185, in new
    obj = await new()
          ^^^^^^^^^^^
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/jobs.py", line 158, in new
    obj = new_job()
          ^^^^^^^^^
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/jobs.py", line 151, in <lambda>
    new_job = lambda: Job(
                      ^^^^
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/jobs.py", line 254, in __init__
    ) = self.rule.expand_input(self.wildcards_dict, groupid=groupid)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/rules.py", line 795, in expand_input
    incomplete = self._apply_wildcards(
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/rules.py", line 707, in _apply_wildcards
    item, incomplete = self.apply_input_function(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/rules.py", line 665, in apply_input_function
    res, incomplete = apply_func(res)
                      ^^^^^^^^^^^^^^^
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/rules.py", line 659, in apply_func
    raise InputFunctionException(e, rule=self, wildcards=wildcards)
snakemake.exceptions.InputFunctionException: Error:
  IndexError: single positional indexer is out-of-bounds
Wildcards:
  sample=WT_REP1_control/WT_REP1_control
Traceback:
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 54, in get_paired_trimmed_fq
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/pandas/core/indexing.py", line 1191, in __getitem__
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/pandas/core/indexing.py", line 1752, in _getitem_axis
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/pandas/core/indexing.py", line 1685, in _validate_integer (rule align_paired, line 263, /home/lucianhu/rna_snakemake/test_ting/Snakefile)

InputFunctionException in rule align_paired in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 158:
Error:
  IndexError: single positional indexer is out-of-bounds
Wildcards:
  sample=WT_REP1_control/WT_REP1_control
Traceback:
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 54, in get_paired_trimmed_fq
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/pandas/core/indexing.py", line 1191, in __getitem__
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/pandas/core/indexing.py", line 1752, in _getitem_axis
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/pandas/core/indexing.py", line 1685, in _validate_integer (rule align_paired, line 263, /home/lucianhu/rna_snakemake/test_ting/Snakefile)
