Building DAG of jobs...
shared_storage_local_copies: True
remote_exec: False
Using shell: /usr/bin/bash
Provided cores: 24
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job stats:
job                            count
---------------------------  -------
align_paired                       3
align_single                       3
all                                1
picard_mark_duplicates             6
samtools_markdup_processing        6
samtools_process                   6
star_genome_generate               1
stringtie                          6
total                             32

Resources before job selection: {'_cores': 24, '_nodes': 9223372036854775807}
Ready jobs (1)
Select jobs to execute...
Using greedy selector because only single job has to be scheduled.
Selected jobs (1)
Resources after job selection: {'_cores': 12, '_nodes': 9223372036854775806}
Execute 1 jobs...

[Sun Aug 18 20:18:49 2024]
Job 3: Creating a reference genome index
Reason: Updated input files: resources/annotation.filtered.gtf

Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 185, in __rule_star_genome_generate
    threads: 8
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        samtools faidx resources/genome.fa &> logs/star_genome_generate.log
        NUM_BASES=$(gawk '{sum = sum + $2}END{if ((log(sum)/log(2))/2 - 1 > 14) {printf "%.0f", 14} else {printf "%.0f", (log(sum)/log(2))/2 - 1}}' resources/genome.fa.fai)
        STAR --runMode genomeGenerate --genomeDir resources/star_index --genomeFastaFiles resources/genome.fa --sjdbGTFfile resources/annotation.filtered.gtf --runThreadN 12 --genomeSAindexNbases $NUM_BASES --limitGenomeGenerateRAM 77209411328 &>> logs/star_genome_generate.log' returned non-zero exit status 127.

Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 185, in __rule_star_genome_generate
    threads: 8
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        samtools faidx resources/genome.fa &> logs/star_genome_generate.log
        NUM_BASES=$(gawk '{sum = sum + $2}END{if ((log(sum)/log(2))/2 - 1 > 14) {printf "%.0f", 14} else {printf "%.0f", (log(sum)/log(2))/2 - 1}}' resources/genome.fa.fai)
        STAR --runMode genomeGenerate --genomeDir resources/star_index --genomeFastaFiles resources/genome.fa --sjdbGTFfile resources/annotation.filtered.gtf --runThreadN 12 --genomeSAindexNbases $NUM_BASES --limitGenomeGenerateRAM 77209411328 &>> logs/star_genome_generate.log' returned non-zero exit status 127.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 261, in _callback
    raise ex
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 247, in cached_or_run
    run_func(*args)
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 459, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 124:
Command 'set -euo pipefail;  
        samtools faidx resources/genome.fa &> logs/star_genome_generate.log
        NUM_BASES=$(gawk '{sum = sum + $2}END{if ((log(sum)/log(2))/2 - 1 > 14) {printf "%.0f", 14} else {printf "%.0f", (log(sum)/log(2))/2 - 1}}' resources/genome.fa.fai)
        STAR --runMode genomeGenerate --genomeDir resources/star_index --genomeFastaFiles resources/genome.fa --sjdbGTFfile resources/annotation.filtered.gtf --runThreadN 12 --genomeSAindexNbases $NUM_BASES --limitGenomeGenerateRAM 77209411328 &>> logs/star_genome_generate.log' returned non-zero exit status 127.

RuleException:
CalledProcessError in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 124:
Command 'set -euo pipefail;  
        samtools faidx resources/genome.fa &> logs/star_genome_generate.log
        NUM_BASES=$(gawk '{sum = sum + $2}END{if ((log(sum)/log(2))/2 - 1 > 14) {printf "%.0f", 14} else {printf "%.0f", (log(sum)/log(2))/2 - 1}}' resources/genome.fa.fai)
        STAR --runMode genomeGenerate --genomeDir resources/star_index --genomeFastaFiles resources/genome.fa --sjdbGTFfile resources/annotation.filtered.gtf --runThreadN 12 --genomeSAindexNbases $NUM_BASES --limitGenomeGenerateRAM 77209411328 &>> logs/star_genome_generate.log' returned non-zero exit status 127.
[Sun Aug 18 20:18:49 2024]
Error in rule star_genome_generate:
    jobid: 3
    input: resources/annotation.filtered.gtf, resources/genome.fa
    output: resources/star_index
    log: logs/star_genome_generate.log (check log file(s) for error details)
    conda-env: /home/lucianhu/rna_snakemake/test_ting/.snakemake/conda/1f835baae0b7b062716b90b833a307f5_
    shell:
        
        samtools faidx resources/genome.fa &> logs/star_genome_generate.log
        NUM_BASES=$(gawk '{sum = sum + $2}END{if ((log(sum)/log(2))/2 - 1 > 14) {printf "%.0f", 14} else {printf "%.0f", (log(sum)/log(2))/2 - 1}}' resources/genome.fa.fai)
        STAR --runMode genomeGenerate --genomeDir resources/star_index --genomeFastaFiles resources/genome.fa --sjdbGTFfile resources/annotation.filtered.gtf --runThreadN 12 --genomeSAindexNbases $NUM_BASES --limitGenomeGenerateRAM 77209411328 &>> logs/star_genome_generate.log
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-08-18T201849.053718.snakemake.log
unlocking
removing lock
removing lock
removed all locks
Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/cli.py", line 2103, in args_to_api
    dag_api.execute_workflow(
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/api.py", line 594, in execute_workflow
    workflow.execute(
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/workflow.py", line 1286, in execute
    raise WorkflowError("At least one job did not complete successfully.")
snakemake_interface_common.exceptions.WorkflowError: At least one job did not complete successfully.

WorkflowError:
At least one job did not complete successfully.
