Building DAG of jobs...
Forcing incomplete files:
	results/align/bam_original/WT_REP2_control/WT_REP2_control.Aligned.out.bam
	results/align/bam_original/WT_REP2_control/WT_REP2_control.Aligned.toTranscriptome.out.bam
shared_storage_local_copies: True
remote_exec: False
Using shell: /usr/bin/bash
Provided cores: 24
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job stats:
job                            count
---------------------------  -------
align_paired                       1
all                                1
filter_gtf                         1
picard_mark_duplicates             1
samtools_markdup_processing        1
samtools_process                   1
stringtie                          6
total                             12

Resources before job selection: {'_cores': 24, '_nodes': 9223372036854775807}
Ready jobs (2)
Select jobs to execute...
Selected jobs (2)
Resources after job selection: {'_cores': 11, '_nodes': 9223372036854775805}
Execute 2 jobs...

[Sun Aug 18 20:01:51 2024]
localrule filter_gtf:
    input: resources/annotation.gtf, resources/genome.fa
    output: resources/annotation.filtered.gtf
    log: logs/filter_gtf.log
    jobid: 32
    reason: Missing output files: resources/annotation.filtered.gtf
    resources: tmpdir=/tmp


[Sun Aug 18 20:01:51 2024]
Job 3: WT_REP2_control: Aligning on paired-end FASTQ files...
Reason: Forced execution

Completion of job ['filter_gtf'] reported to scheduler.
Waiting at most 5 seconds for missing files.
still missing files, waiting...
still missing files, waiting...
still missing files, waiting...
still missing files, waiting...
still missing files, waiting...
Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/dag.py", line 673, in check_and_touch_output
    await wait_for_files(
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/io.py", line 985, in wait_for_files
    raise IOError(
OSError: Missing files after 5 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
resources/annotation.filtered.gtf (missing locally, parent dir contents: star_index, annotation.filtered.filtered.gtf, annotation.gtf, genome.fa)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/scheduler.py", line 334, in postprocess
    await job.postprocess(
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/jobs.py", line 1133, in postprocess
    await self.dag.check_and_touch_output(
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/dag.py", line 680, in check_and_touch_output
    raise MissingOutputException(
snakemake.exceptions.MissingOutputException: Job 32  completed successfully, but some output files are missing. Missing files after 5 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
resources/annotation.filtered.gtf (missing locally, parent dir contents: star_index, annotation.filtered.filtered.gtf, annotation.gtf, genome.fa)

MissingOutputException in rule filter_gtf in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 362:
Job 32  completed successfully, but some output files are missing. Missing files after 5 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
resources/annotation.filtered.gtf (missing locally, parent dir contents: star_index, annotation.filtered.filtered.gtf, annotation.gtf, genome.fa)
Terminating processes on user request, this might take some time.
Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 340, in __rule_align_paired
    "{wildcards.sample}: Running Samtools to mark duplicate reads"
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        # Run STAR alignment
        STAR --genomeDir resources/star_index              --readFilesIn results/trimmed/WT_REP2_control_trimmed_R1.fq.gz results/trimmed/WT_REP2_control_trimmed_R2.fq.gz              --runThreadN 12              --genomeLoad NoSharedMemory              --outFileNamePrefix results/align/bam_original/WT_REP2_control/WT_REP2_control.              --sjdbGTFfile resources/annotation.gtf              --outSAMattrRGline 'ID:WT_REP2_control' 'SM:WT_REP2_control'              --outSAMtype BAM Unsorted              --quantMode TranscriptomeSAM              --twopassMode Basic              --readFilesCommand zcat              --runRNGseed 0              --alignSJDBoverhangMin 1              --outSAMattributes NH HI AS NM MD              --outSAMstrandField intronMotif              --quantTranscriptomeSAMoutput BanSingleEnd              --outFilterMultimapNmax 1              --outFilterMismatchNmax 3              --peOverlapNbasesMin 10              --alignSplicedMateMapLminOverLmate 0.5              --chimSegmentMin 10              --chimOutType WithinBAM SoftClip              --chimJunctionOverhangMin 10              --chimScoreMin 1              --chimScoreDropMax 30              --chimScoreJunctionNonGTAG 0              --chimScoreSeparation 1              --alignSJstitchMismatchNmax 5 -1 5 5              --chimSegmentReadGapMax 3 &> logs/star_align/WT_REP2_control.star_align.log' died with <Signals.SIGINT: 2>.

Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 340, in __rule_align_paired
    "{wildcards.sample}: Running Samtools to mark duplicate reads"
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        # Run STAR alignment
        STAR --genomeDir resources/star_index              --readFilesIn results/trimmed/WT_REP2_control_trimmed_R1.fq.gz results/trimmed/WT_REP2_control_trimmed_R2.fq.gz              --runThreadN 12              --genomeLoad NoSharedMemory              --outFileNamePrefix results/align/bam_original/WT_REP2_control/WT_REP2_control.              --sjdbGTFfile resources/annotation.gtf              --outSAMattrRGline 'ID:WT_REP2_control' 'SM:WT_REP2_control'              --outSAMtype BAM Unsorted              --quantMode TranscriptomeSAM              --twopassMode Basic              --readFilesCommand zcat              --runRNGseed 0              --alignSJDBoverhangMin 1              --outSAMattributes NH HI AS NM MD              --outSAMstrandField intronMotif              --quantTranscriptomeSAMoutput BanSingleEnd              --outFilterMultimapNmax 1              --outFilterMismatchNmax 3              --peOverlapNbasesMin 10              --alignSplicedMateMapLminOverLmate 0.5              --chimSegmentMin 10              --chimOutType WithinBAM SoftClip              --chimJunctionOverhangMin 10              --chimScoreMin 1              --chimScoreDropMax 30              --chimScoreJunctionNonGTAG 0              --chimScoreSeparation 1              --alignSJstitchMismatchNmax 5 -1 5 5              --chimSegmentReadGapMax 3 &> logs/star_align/WT_REP2_control.star_align.log' died with <Signals.SIGINT: 2>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 261, in _callback
    raise ex
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 247, in cached_or_run
    run_func(*args)
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 459, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 180:
Command 'set -euo pipefail;  
        # Run STAR alignment
        STAR --genomeDir resources/star_index              --readFilesIn results/trimmed/WT_REP2_control_trimmed_R1.fq.gz results/trimmed/WT_REP2_control_trimmed_R2.fq.gz              --runThreadN 12              --genomeLoad NoSharedMemory              --outFileNamePrefix results/align/bam_original/WT_REP2_control/WT_REP2_control.              --sjdbGTFfile resources/annotation.gtf              --outSAMattrRGline 'ID:WT_REP2_control' 'SM:WT_REP2_control'              --outSAMtype BAM Unsorted              --quantMode TranscriptomeSAM              --twopassMode Basic              --readFilesCommand zcat              --runRNGseed 0              --alignSJDBoverhangMin 1              --outSAMattributes NH HI AS NM MD              --outSAMstrandField intronMotif              --quantTranscriptomeSAMoutput BanSingleEnd              --outFilterMultimapNmax 1              --outFilterMismatchNmax 3              --peOverlapNbasesMin 10              --alignSplicedMateMapLminOverLmate 0.5              --chimSegmentMin 10              --chimOutType WithinBAM SoftClip              --chimJunctionOverhangMin 10              --chimScoreMin 1              --chimScoreDropMax 30              --chimScoreJunctionNonGTAG 0              --chimScoreSeparation 1              --alignSJstitchMismatchNmax 5 -1 5 5              --chimSegmentReadGapMax 3 &> logs/star_align/WT_REP2_control.star_align.log' died with <Signals.SIGINT: 2>.

RuleException:
CalledProcessError in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 180:
Command 'set -euo pipefail;  
        # Run STAR alignment
        STAR --genomeDir resources/star_index              --readFilesIn results/trimmed/WT_REP2_control_trimmed_R1.fq.gz results/trimmed/WT_REP2_control_trimmed_R2.fq.gz              --runThreadN 12              --genomeLoad NoSharedMemory              --outFileNamePrefix results/align/bam_original/WT_REP2_control/WT_REP2_control.              --sjdbGTFfile resources/annotation.gtf              --outSAMattrRGline 'ID:WT_REP2_control' 'SM:WT_REP2_control'              --outSAMtype BAM Unsorted              --quantMode TranscriptomeSAM              --twopassMode Basic              --readFilesCommand zcat              --runRNGseed 0              --alignSJDBoverhangMin 1              --outSAMattributes NH HI AS NM MD              --outSAMstrandField intronMotif              --quantTranscriptomeSAMoutput BanSingleEnd              --outFilterMultimapNmax 1              --outFilterMismatchNmax 3              --peOverlapNbasesMin 10              --alignSplicedMateMapLminOverLmate 0.5              --chimSegmentMin 10              --chimOutType WithinBAM SoftClip              --chimJunctionOverhangMin 10              --chimScoreMin 1              --chimScoreDropMax 30              --chimScoreJunctionNonGTAG 0              --chimScoreSeparation 1              --alignSJstitchMismatchNmax 5 -1 5 5              --chimSegmentReadGapMax 3 &> logs/star_align/WT_REP2_control.star_align.log' died with <Signals.SIGINT: 2>.
[Sun Aug 18 20:02:12 2024]
Error in rule align_paired:
    jobid: 3
    input: results/trimmed/WT_REP2_control_trimmed_R1.fq.gz, results/trimmed/WT_REP2_control_trimmed_R2.fq.gz, resources/annotation.gtf, resources/star_index
    output: results/align/bam_original/WT_REP2_control/WT_REP2_control.Aligned.out.bam, results/align/bam_original/WT_REP2_control/WT_REP2_control.Aligned.toTranscriptome.out.bam
    log: logs/star_align/WT_REP2_control.star_align.log (check log file(s) for error details)
    conda-env: /home/lucianhu/rna_snakemake/test_ting/.snakemake/conda/1f835baae0b7b062716b90b833a307f5_
    shell:
        
        # Run STAR alignment
        STAR --genomeDir resources/star_index              --readFilesIn results/trimmed/WT_REP2_control_trimmed_R1.fq.gz results/trimmed/WT_REP2_control_trimmed_R2.fq.gz              --runThreadN 12              --genomeLoad NoSharedMemory              --outFileNamePrefix results/align/bam_original/WT_REP2_control/WT_REP2_control.              --sjdbGTFfile resources/annotation.gtf              --outSAMattrRGline 'ID:WT_REP2_control' 'SM:WT_REP2_control'              --outSAMtype BAM Unsorted              --quantMode TranscriptomeSAM              --twopassMode Basic              --readFilesCommand zcat              --runRNGseed 0              --alignSJDBoverhangMin 1              --outSAMattributes NH HI AS NM MD              --outSAMstrandField intronMotif              --quantTranscriptomeSAMoutput BanSingleEnd              --outFilterMultimapNmax 1              --outFilterMismatchNmax 3              --peOverlapNbasesMin 10              --alignSplicedMateMapLminOverLmate 0.5              --chimSegmentMin 10              --chimOutType WithinBAM SoftClip              --chimJunctionOverhangMin 10              --chimScoreMin 1              --chimScoreDropMax 30              --chimScoreJunctionNonGTAG 0              --chimScoreSeparation 1              --alignSJstitchMismatchNmax 5 -1 5 5              --chimSegmentReadGapMax 3 &> logs/star_align/WT_REP2_control.star_align.log
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Complete log: .snakemake/log/2024-08-18T200151.013444.snakemake.log
unlocking
removing lock
removing lock
removed all locks
Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/cli.py", line 2103, in args_to_api
    dag_api.execute_workflow(
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/api.py", line 594, in execute_workflow
    workflow.execute(
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/workflow.py", line 1286, in execute
    raise WorkflowError("At least one job did not complete successfully.")
snakemake_interface_common.exceptions.WorkflowError: At least one job did not complete successfully.

WorkflowError:
At least one job did not complete successfully.
